name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Test-branch  
  pull_request:
    branches:
      - main
      - Test-branch  

jobs:
  commitlint:
    name: Enforce Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Commitlint
        uses: wagoid/commitlint-github-action@v5

  lint-test:
    name: Lint & Test Code
    runs-on: ubuntu-latest
    needs: commitlint  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: lint-test  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production)
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        if: github.ref == 'refs/heads/main'

      - name: Deploy to Vercel (Preview)
        run: vercel --token ${{ secrets.VERCEL_TOKEN }}
        if: github.ref == 'refs/heads/Test-branch'  
