name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Test-branch  
  pull_request:
    branches:
      - main
      - Test-branch  

jobs:
  commitlint:
    name: Enforce Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Commitlint
        uses: wagoid/commitlint-github-action@v5

  lint-test:
    name: Lint & Test Code
    runs-on: ubuntu-latest
    needs: commitlint  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: lint-test  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Netlify CLI
        run: npm install --global netlify-cli

      - name: Deploy to Netlify (Production)
        run: netlify deploy --prod --dir=dist --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}
        if: github.ref == 'refs/heads/main'

      - name: Deploy to Netlify (Preview)
        run: netlify deploy --dir=dist --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}
        if: github.ref == 'refs/heads/Test-branch'
